### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by mikaelvilen** [Jouchef/Partiokokoustilan-tyokalu#1]
Sovellusta oli sujuvaa ja mukava käyttää. Sovellus oli selkeästi toteutettu ja kaikki toteutetut toiminnot toimivat.

Käyttäjätunnuksen luonnissa voisi käyttää UNIQUE -määrettä, jotta ei voisi luoda kahta samaa tunnusta.
Päiväkirjamerkintä lomakkeen pystyi lähettämään tyhjänä, tähän voisi tehdä validoinnin html:n puolella.
Inventaarion tuotteen lisäämisen lomakkeen pystyi myös lähettämään tyhjänä, josta seurasi internal server error 500.

Koodia oli helppo lukea, selkeästi toteutettu. Päiväkirjamerkinnässä voi lisätä minkä tahansa nimen kirjoittajaksi, olisiko tämä parempi toteuttaa tietokannasta niin, että käyttäjä lisää itselleen käyttäjänimen tunnuksen luonnin yhteydessä, jotta päiväkirjamerkinnän kirjoittaja on aina kirjautunut käyttäjä?

Hyvä sovellus!

**Comment by Jouchef** [comment]
Kiitos kehittävistä kommenteista!
