### ISSUE TITLE
Vertaisarviointi Peer review 2

### ISSUE THREAD

**Issue by sinilandia** [Jouchef/Partiokokoustilan-tyokalu#2]
Hi Joosef,

Loving this app! It's easy to use and easy to understand. I appreciate how you've made the admin page so that even people who don't know SQL can be admins. I tested out your app and added some comments there. Here's a more comprehensive list:

1) It's possible to add products into the inventory with 0 amount.
2) In the diary page, you could list the diary entries according to date instead of showing newest first.
3) In the burrow booking, I think it'd be helpful to see the total amount of users. If the max amount is 100, now it is possible to add more than that when you sum up the different user types (adult/youngster).
4) Your code makes sense and the different files are easy to understand. I even learned something new! After reviewing your work, I'll be googling these functools and wraps. :)
5) For the visuals, I think a bit of bootstrap will be enough and adding your scout logo.
6) Sometimes it was a bit challenging to notice the buttons since they weren't clearly styled as buttons or the navigation "Kotisivulle" was a bit hidden since it looked like normal text.
7) The error messages made sense and I think I tested them all out so you shouldn't be missing any of those.

All in all, I think you're well ahead with your app. Just a final stretch and the course is done. Good luck! :)

Best,
Sini

**Comment by Jouchef** [comment]
Hi Sini,

Sorry to answer you this late. I really appreciate your feedback and it's certainly going to good use!

I peeked at your project and that seemed quite professional!

Best,
Joosef
